class AppStrings {
  // English Strings
  static const Map<String, String> en = {
    'app_name': 'LearnHub',
    'home': 'Home',
    'courses': 'Courses',
    'profile': 'Profile',
    'search': 'Search courses...',
    'popular_courses': 'Popular Courses',
    'all_courses': 'All Courses',
    'continue_learning': 'Continue Learning',
    'lessons': 'Lessons',
    'quiz': 'Quiz',
    'start_quiz': 'Start Quiz',
    'retake_quiz': 'Retake Quiz',
    'next': 'Next',
    'previous': 'Previous',
    'submit': 'Submit',
    'score': 'Score',
    'correct': 'Correct',
    'incorrect': 'Incorrect',
    'completed': 'Completed',
    'in_progress': 'In Progress',
    'not_started': 'Not Started',
    'settings': 'Settings',
    'language': 'Language',
    'dark_mode': 'Dark Mode',
    'about': 'About',
    'version': 'Version',
    'reset_progress': 'Reset Progress',
    'confirm_reset': 'Are you sure you want to reset all progress?',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'no_courses': 'No courses found',
    'loading': 'Loading...',
    'error': 'Something went wrong',
    'try_again': 'Try Again',
    'watch_now': 'Watch Now',
    'mark_complete': 'Mark as Complete',
    'already_completed': 'Already Completed',
    'course_progress': 'Course Progress',
    'total_lessons': 'Total Lessons',
    'completed_lessons': 'Completed Lessons',
    'quiz_score': 'Quiz Score',
    'best_score': 'Best Score',
    'instructor': 'Instructor',
    'duration': 'Duration',
    'difficulty': 'Difficulty',
    'beginner': 'Beginner',
    'intermediate': 'Intermediate',
    'advanced': 'Advanced',
    'question': 'Question',
    'of': 'of',
    'finish': 'Finish',
    'congratulations': 'Congratulations!',
    'quiz_completed': 'Quiz Completed',
    'your_score': 'Your Score',
    'back_to_course': 'Back to Course',
    'my_progress': 'My Progress',
    'lessons_completed': 'Lessons Completed',
    'quizzes_taken': 'Quizzes Taken',
  };

  // Khmer Strings
  static const Map<String, String> kh = {
    'app_name': 'LearnHub',
    'home': 'ទំព័រដើម',
    'courses': 'វគ្គសិក្សា',
    'profile': 'ប្រវត្តិរូប',
    'search': 'ស្វែងរកវគ្គសិក្សា...',
    'popular_courses': 'វគ្គសិក្សាពេញនិយម',
    'all_courses': 'វគ្គសិក្សាទាំងអស់',
    'continue_learning': 'បន្តការសិក្សា',
    'lessons': 'មេរៀន',
    'quiz': 'កម្រងសំណួរ',
    'start_quiz': 'ចាប់ផ្តើមកម្រងសំណួរ',
    'retake_quiz': 'ធ្វើកម្រងសំណួរម្តងទៀត',
    'next': 'បន្ទាប់',
    'previous': 'មុន',
    'submit': 'ដាក់ស្នើ',
    'score': 'ពិន្ទុ',
    'correct': 'ត្រឹមត្រូវ',
    'incorrect': 'មិនត្រឹមត្រូវ',
    'completed': 'បានបញ្ចប់',
    'in_progress': 'កំពុងដំណើរការ',
    'not_started': 'មិនទាន់ចាប់ផ្តើម',
    'settings': 'ការកំណត់',
    'language': 'ភាសា',
    'dark_mode': 'របៀបងងឹត',
    'about': 'អំពី',
    'version': 'កំណែ',
    'reset_progress': 'កំណត់វឌ្ឍនភាពឡើងវិញ',
    'confirm_reset': 'តើអ្នកប្រាកដថាចង់កំណត់វឌ្ឍនភាពទាំងអស់ឡើងវិញមែនទេ?',
    'cancel': 'បោះបង់',
    'confirm': 'បញ្ជាក់',
    'no_courses': 'រកមិនឃើញវគ្គសិក្សា',
    'loading': 'កំពុងផ្ទុក...',
    'error': 'មានបញ្ហាកើតឡើង',
    'try_again': 'ព្យាយាមម្តងទៀត',
    'watch_now': 'មើលឥឡូវ',
    'mark_complete': 'សម្គាល់ថាបានបញ្ចប់',
    'already_completed': 'បានបញ្ចប់រួចហើយ',
    'course_progress': 'វឌ្ឍនភាពវគ្គសិក្សា',
    'total_lessons': 'មេរៀនសរុប',
    'completed_lessons': 'មេរៀនបានបញ្ចប់',
    'quiz_score': 'ពិន្ទុកម្រងសំណួរ',
    'best_score': 'ពិន្ទុល្អបំផុត',
    'instructor': 'គ្រូបង្រៀន',
    'duration': 'រយៈពេល',
    'difficulty': 'កម្រិតលំបាក',
    'beginner': 'ចាប់ផ្តើម',
    'intermediate': 'មធ្យម',
    'advanced': 'កម្រិតខ្ពស់',
    'question': 'សំណួរ',
    'of': 'នៃ',
    'finish': 'បញ្ចប់',
    'congratulations': 'អបអរសាទរ!',
    'quiz_completed': 'បានបញ្ចប់កម្រងសំណួរ',
    'your_score': 'ពិន្ទុរបស់អ្នក',
    'back_to_course': 'ត្រឡប់ទៅវគ្គសិក្សា',
    'my_progress': 'វឌ្ឍនភាពរបស់ខ្ញុំ',
    'lessons_completed': 'មេរៀនបានបញ្ចប់',
    'quizzes_taken': 'កម្រងសំណួរបានធ្វើ',
  };

  static String get(String key, String language) {
    if (language == 'kh') {
      return kh[key] ?? en[key] ?? key;
    }
    return en[key] ?? key;
  }
}
